[build]
  command = "npm install && npm run build"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/redirect.html"
  status = 200
  force = false
  conditions = {Language = ["es"], Country = []}

# Manejo de SPA (Single Page Application)
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# 404 personalizada
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
