[build]
  publish = "."  # ¡Importante! Busca archivos en la raíz
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false  # Permite acceso directo a login.html y redirect.html

[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404
