[build]
  publish = "public"
  functions = "netlify/functions"

# Redirige todas las rutas al login, excepto /redirect y /404
[[redirects]]
  from = "/*"
  to = "/login.html"
  status = 200
  conditions = {Role = "anonymous"}  # Solo para usuarios no autenticados
  force = true

# Excepciones (rutas públicas)
[[redirects]]
  from = "/redirect"
  to = "/redirect.html"
  status = 200

[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404
