[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/redirect.html"
  status = 200
  force = false

[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404
